### ISSUE TITLE
ImportError: cannot import name legacy_seq2seq

### ISSUE THREAD

**Issue by BSVogler** [sherjilozair/char-rnn-tensorflow#87]
Hi!

I just downloaded the code and tried to run it with the train.py with tf-v1.0. I think it should train the Shakespeare example. Readme says default parameters. However it fails

```
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from model import Model
  File "/opt/gpu-project/char-rnn-tensorflow/model.py", line 3, in <module>
    from tensorflow.contrib import legacy_seq2seq
ImportError: cannot import name legacy_seq2seq
```

**Comment by BSVogler** [comment]
Hmm, my fault. I ran it with `python` and not with `python3`.

**Comment by hugovk** [comment]
This should work with Python 2.7, just make sure you have Tensorflow 1.0 (and not, say, the latest Tensorflow 1.2).

```bash
pip install tensorflow==1.0
```
